"""empty message

Revision ID: 09ae4e63ae8b
Revises: afbc725ab082
Create Date: 2017-02-23 18:44:13.094097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ae4e63ae8b'
down_revision = 'afbc725ab082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'date')
    # ### end Alembic commands ###
