"""empty message

Revision ID: 45371360cd4e
Revises: 09ae4e63ae8b
Create Date: 2017-02-23 19:09:43.342667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45371360cd4e'
down_revision = '09ae4e63ae8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('date_stamp', sa.Date(), nullable=True))
    op.drop_column('product', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('date', sa.DATE(), nullable=True))
    op.drop_column('product', 'date_stamp')
    # ### end Alembic commands ###
